import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/components/navbar";
import LogosprovView from "@/components/logosprov";
import FooterView from "@/components/footer/footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      {/* <body className={inter.className}> */}
      <body className="h-screen font-sans  bg-white transition-colors duration-500 ease-in-out ">
      <div className="bg-white">
        <LogosprovView />
        <Navbar />
        {children}
      

        <FooterView /> 

      </div>
        
      </body>
    </html>
  )
}
